[package]
name = "gui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess_logic = { path = "../chess_logic" }
ggez = "0.5.1"
glam = "0.12.0"
